// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkhbpvspsasbdydybxhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraGJwdnNwc2FzYmR5ZHlieGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjMwMDcsImV4cCI6MjA2MTMzOTAwN30.saFNRMspfzoPqcR-1LDRvMSenrbwoV_kxOlsWM7n7iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);